spring.application.name=TransactionManagement


# MySQL Database Configuration
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/transaction123
spring.datasource.username=root
spring.datasource.password=root
#
## MySQL Driver (Usually auto-detected but can be added)
#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate Settings
#
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=sunil
#spring.security.user.password=sunil

