spring.application.name=SpringCloudWelcomeApi
spring.boot.admin.client.url=http://localhost:1111/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*

#8086 greet ,welcome 55 56 57
#eureka -> we need annoation , eureka client depency , defualt else automatic registration 
#admin -> dependency , spring.boot.admin.client.url
#zipkin -> we need to make server up , depency