spring.application.name=Resilence4jServiceA

server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.Resilence4jServiceB.registerHealthIndicator=true

# Sliding Window
resilience4j.circuitbreaker.instances.Resilence4jServiceB.slidingWindowSize=5

# Failure threshold
resilience4j.circuitbreaker.instances.Resilence4jServiceB.failureRateThreshold=50

# Wait before HALF_OPEN
resilience4j.circuitbreaker.instances.Resilence4jServiceB.waitDurationInOpenState=5s

# HALF_OPEN allowed calls
resilience4j.circuitbreaker.instances.Resilence4jServiceB.permittedNumberOfCallsInHalfOpenState=3

# Minimum calls before evaluating
resilience4j.circuitbreaker.instances.Resilence4jServiceB.minimumNumberOfCalls=5

# Automatic transition
resilience4j.circuitbreaker.instances.Resilence4jServiceB.automaticTransitionFromOpenToHalfOpenEnabled=true
