spring.application.name=SpringCloudGreetApi
spring.boot.admin.client.url=http://localhost:1111/
server.port=8086
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*
#greet->welcome (8055 , 8056 ,8057)
